### PR TITLE
Fixes microsoft/commercial-marketplace-client-dotnet#56

### PR DESCRIPTION
**Pull request by arindamdat**

### CODE REVIEW

**Comment by arindamdat** [comment]
@microsoft-github-policy-service agree

**Comment by arindamdat** [comment]
@Ercenk @scseely @code4clouds @microsoftopensource @dstarr , I submitted this PR as a fix for #56

**Comment by arindamdat** [comment]
Is anyone there?

**Comment by santhoshb-msft** [comment]
Hi @arindamdat - quick question, are the changes outcome of autorest ?

**Comment by santhoshb-msft** [comment]
Fixed part of #58 Thank you @arindamdat !

**Pull request closed without merging**
